# Generated by Django 4.0.5 on 2022-07-05 01:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_teacherleave_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 6, 53, 15, 667954)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
    ]
