# Generated by Django 4.0.5 on 2022-07-05 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_teacherleave_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 6, 59, 30, 944353)),
        ),
    ]
