# Generated by Django 4.0.5 on 2022-07-06 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_teacherleave_date_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Staff Profile'},
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 8, 26, 42, 741285)),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.parentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacherprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='classes',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.class'),
            preserve_default=False,
        ),
    ]
