# Generated by Django 4.0.5 on 2022-07-06 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_class_alter_teacherprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 8, 28, 52, 393684)),
        ),
    ]
